/* ----------------------------------------------
 * Generated by Animista on 2022-6-8 14:43:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

import { styled } from "@mui/system";
import { Typography, keyframes } from "@mui/material";

const keyframe = keyframes`
50% {
  opacity: 0.7;
}
100% {
  opacity: 1;
}
`;

export const ScaleUpCenterAnimation = styled(Typography)(({}) => ({
  // visibility: !action && "hidden",
  "&:hover": {
    animation: `${keyframe} 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both`,
  },
}));
